#pragma once
#include <Arduino.h>
#include <ESP32-HUB75-MatrixPanel-I2S-DMA.h>
#include "GameBase.h"
#include "ControllerManager.h"
#include "config.h"

// Include converted OpenMoji data (generated by convert_emojis_pure.py)
// If EmojisData.h doesn't exist yet, fall back to embedded emojis
#ifdef __has_include
    #if __has_include("EmojisData.h")
        #include "EmojisData.h"
        #define USE_OPENMOJI_DATA
    #endif
#endif

/**
 * EmojisGame - Displays colorful OpenMoji emojis fullscreen
 * Source: https://openmoji.org (CC BY-SA 4.0)
 */
class EmojisGame : public GameBase {
private:
#ifdef USE_OPENMOJI_DATA
    // Use converted OpenMoji data (64x64 RGB565 arrays)
    int currentIdx;
    static const int EMOJI_SIZE = 64;

    /**
     * Compute the bounding box of "visible" (non-zero) pixels in the emoji bitmap.
     *
     * Why this exists:
     * - Even when the bitmap is 64x64, the *content* can be shifted inside the canvas
     *   depending on SVG bounds / rendering quirks.
     * - Centering at runtime ensures emojis appear centered immediately, even with
     *   older generated `EmojisData.h` files.
     *
     * Notes:
     * - Returned bounds are inclusive: [minX..maxX], [minY..maxY].
     */
    static inline void computeVisibleBoundsDisplaySpace(
        const uint16_t* emojiData,
        int& outMinX, int& outMinY,
        int& outMaxX, int& outMaxY
    ) {
        outMinX = EMOJI_SIZE;
        outMinY = EMOJI_SIZE;
        outMaxX = -1;
        outMaxY = -1;

        for (int y = 0; y < EMOJI_SIZE; y++) {
            const int rowBase = y * EMOJI_SIZE;
            for (int x = 0; x < EMOJI_SIZE; x++) {
                const uint16_t px = emojiData[rowBase + x];
                if (px == 0) continue; // treat RGB565 0 as transparent
                if (x < outMinX) outMinX = x;
                if (x > outMaxX) outMaxX = x;
                if (y < outMinY) outMinY = y;
                if (y > outMaxY) outMaxY = y;
            }
        }

        // If the emoji is entirely transparent (shouldn't happen), fall back to full canvas.
        if (outMaxX < outMinX || outMaxY < outMinY) {
            outMinX = 0;
            outMinY = 0;
            outMaxX = EMOJI_SIZE - 1;
            outMaxY = EMOJI_SIZE - 1;
        }
    }
#else
    // Fallback: simple embedded emojis if conversion hasn't been run
    struct Emoji {
        const uint16_t* data;  // 16x16 RGB565 bitmap
    };
    static const uint16_t emojiSmile[256];
    static const uint16_t emojiHeart[256];
    static const uint16_t emojiStar[256];
    static const uint16_t emojiMusic[256];
    static const uint16_t emojiSun[256];
    const Emoji emojis[5] = {
        { emojiSmile }, { emojiHeart }, { emojiStar }, { emojiMusic }, { emojiSun }
    };
    int currentIdx;
    static const int EMOJI_SIZE = 16;
#endif

    unsigned long lastChange;
    static const unsigned long CHANGE_INTERVAL = 10000;  // 10s

    void pickRandom() {
#ifdef USE_OPENMOJI_DATA
        currentIdx = random(0, NUM_EMOJIS);
#else
        currentIdx = random(0, 5);
#endif
    }

public:
    EmojisGame() : currentIdx(0), lastChange(0) {}

    void start() override {
        pickRandom();
        lastChange = millis();
    }

    void reset() override {
        start();
    }

    void update(ControllerManager* input) override {
        ControllerPtr ctl = input->getController(0);
        unsigned long now = millis();
        if (now - lastChange > CHANGE_INTERVAL) {
            pickRandom();
            lastChange = now;
        }
        if (ctl) {
            static unsigned long lastNext = 0;
            if (ctl->a() && (now - lastNext > 200)) {
                pickRandom();
                lastChange = now;
                lastNext = now;
            }
        }
    }

    void draw(MatrixPanel_I2S_DMA* display) override {
        display->fillScreen(COLOR_BLACK);

#ifdef USE_OPENMOJI_DATA
        // Draw 64x64 OpenMoji emoji, centered based on *visible* pixels.
        //
        // Why: The bitmap canvas is always 64x64, but the visible emoji pixels can be
        // shifted inside that canvas depending on SVG bounds / renderer behavior.
        // Centering at runtime fixes that regardless of how `EmojisData.h` was generated.
        const uint16_t* emojiData = emoji_arrays[currentIdx];

        int minX, minY, maxX, maxY;
        computeVisibleBoundsDisplaySpace(emojiData, minX, minY, maxX, maxY);
        const int contentW = (maxX - minX + 1);
        const int contentH = (maxY - minY + 1);

        // Center the visible bounds on the physical panel.
        const int baseX = (PANEL_RES_X - contentW) / 2;
        const int baseY = (PANEL_RES_Y - contentH) / 2;

        for (int y = 0; y < EMOJI_SIZE; y++) {
            for (int x = 0; x < EMOJI_SIZE; x++) {
                uint16_t px = emojiData[y * EMOJI_SIZE + x];
                // Only draw non-black pixels (transparency handling)
                if (px != 0) {
                    // Rebase into the content bounds, then shift to centered position.
                    const int dx = baseX + (x - minX);
                    const int dy = baseY + (y - minY);
                    display->drawPixel(dx, dy, px);
                }
            }
        }
#else
        // Fallback: draw simple embedded emojis (scaled to 64x64)
        const Emoji& e = emojis[currentIdx];
        const int scale = 4;  // upscale 16x16 -> 64x64
        for (int y = 0; y < 16; y++) {
            for (int x = 0; x < 16; x++) {
                uint16_t px = e.data[y * 16 + x];
                if (px) {
                    display->fillRect(x * scale, y * scale, scale, scale, px);
                }
            }
        }
#endif
    }

    bool isGameOver() override {
        return false;
    }
};

#ifndef USE_OPENMOJI_DATA
// Fallback: 16x16 RGB565 emoji-inspired bitmaps (soft, bright colors)
const uint16_t EmojisGame::emojiSmile[256] = {
    // yellow face with orange outline and blue eyes
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0xFD20,0xFD20,0xFD20,0xFD20,0xFD20,0xFD20,0xFD20,0,0,0,0,0,
    0,0,0,0xFD20,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFD20,0,0,0,0,
    0,0,0,0xFD20,0xFFE0,0xFFE0,0x001F,0xFFE0,0xFFE0,0x001F,0xFFE0,0xFD20,0,0,0,0,
    0,0,0,0xFD20,0xFFE0,0xFFE0,0x001F,0xFFE0,0xFFE0,0x001F,0xFFE0,0xFD20,0,0,0,0,
    0,0,0,0xFD20,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFD20,0,0,0,0,
    0,0,0,0xFD20,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFD20,0,0,0,0,
    0,0,0,0xFD20,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFD20,0,0,0,0,
    0,0,0,0xFD20,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFD20,0,0,0,0,
    0,0,0,0xFD20,0xFFE0,0xFFE0,0xFFE0,0x07E0,0x07E0,0xFFE0,0xFFE0,0xFD20,0,0,0,0,
    0,0,0,0xFD20,0xFFE0,0xFFE0,0x07E0,0x07E0,0x07E0,0x07E0,0xFFE0,0xFD20,0,0,0,0,
    0,0,0,0xFD20,0xFFE0,0xFFE0,0x07E0,0x07E0,0x07E0,0x07E0,0xFFE0,0xFD20,0,0,0,0,
    0,0,0,0xFD20,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFD20,0,0,0,0,
    0,0,0,0,0xFD20,0xFD20,0xFD20,0xFD20,0xFD20,0xFD20,0xFD20,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
};

const uint16_t EmojisGame::emojiHeart[256] = {
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0xF81F,0xF81F,0,0,0xF81F,0xF81F,0,0,0xF81F,0xF81F,0,0,0,0,
    0,0xF81F,0xFFFF,0xFFFF,0xF81F,0xF81F,0xFFFF,0xFFFF,0xF81F,0xF81F,0xFFFF,0xFFFF,0xF81F,0,0,0,
    0,0xF81F,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xF81F,0,0,0,
    0,0,0xF81F,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xF81F,0,0,0,0,
    0,0,0,0xF81F,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xF81F,0,0,0,0,0,
    0,0,0,0,0xF81F,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xF81F,0,0,0,0,0,0,
    0,0,0,0,0,0xF81F,0xFFFF,0xFFFF,0xF81F,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0xF81F,0xF81F,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
};

const uint16_t EmojisGame::emojiStar[256] = {
    0,0,0,0,0,0xFFE0,0,0,0,0,0xFFE0,0,0,0,0,0,
    0,0,0,0,0xFFE0,0xFFE0,0xFFE0,0,0xFFE0,0xFFE0,0xFFE0,0,0,0,0,0,
    0,0,0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0,0,0,0,
    0,0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0,0,0,
    0,0,0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0,0,0,0,
    0,0,0,0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0,0,0,0,0,
    0,0,0,0,0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0,0,0,0,0,0,
    0,0,0,0,0,0,0xFFE0,0xFFE0,0xFFE0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0xFFE0,0xFFE0,0xFFE0,0,0,0,0,0,0,0,
    0,0,0,0,0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0,0,0,0,0,0,
    0,0,0,0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0,0,0,0,0,
    0,0,0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0,0,0,0,
    0,0,0,0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0,0,0,0,0,
    0,0,0,0,0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0,0,0,0,0,0,
    0,0,0,0,0,0,0xFFE0,0xFFE0,0xFFE0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0xFFE0,0,0,0,0,0,0,0,0,
};

const uint16_t EmojisGame::emojiMusic[256] = {
    0,0,0,0,0,0x780F,0x780F,0x780F,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0x780F,0x780F,0x780F,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0x780F,0x780F,0x780F,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0x780F,0x780F,0x780F,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0x780F,0x780F,0x780F,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0x780F,0x780F,0x780F,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0x780F,0x780F,0x780F,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0x780F,0x780F,0x780F,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0x780F,0x780F,0x780F,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0x780F,0x780F,0x780F,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0x780F,0x780F,0x780F,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0x780F,0x780F,0x780F,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0x780F,0x780F,0x780F,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0x780F,0x780F,0x780F,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0x780F,0x780F,0x780F,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0x780F,0x780F,0x780F,0,0,0,0,0,0,0,0,
};

const uint16_t EmojisGame::emojiSun[256] = {
    0,0,0,0,0,0,0xFD20,0,0xFD20,0,0,0,0,0,0,0,
    0,0,0,0,0,0xFD20,0xFD20,0xFD20,0xFD20,0xFD20,0,0,0,0,0,0,
    0,0,0,0,0xFD20,0xFD20,0xFD20,0xFD20,0xFD20,0xFD20,0xFD20,0,0,0,0,0,
    0,0,0,0xFD20,0xFD20,0xFD20,0xFD20,0xFFE0,0xFD20,0xFD20,0xFD20,0xFD20,0,0,0,0,
    0,0,0,0xFD20,0xFD20,0xFD20,0xFFE0,0xFFE0,0xFFE0,0xFD20,0xFD20,0xFD20,0,0,0,0,
    0,0,0,0xFD20,0xFD20,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFD20,0xFD20,0,0,0,0,
    0,0,0,0xFD20,0xFD20,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFD20,0xFD20,0,0,0,0,
    0,0,0,0xFD20,0xFD20,0xFD20,0xFFE0,0xFFE0,0xFFE0,0xFD20,0xFD20,0xFD20,0,0,0,0,
    0,0,0,0xFD20,0xFD20,0xFD20,0xFFE0,0xFFE0,0xFFE0,0xFD20,0xFD20,0xFD20,0,0,0,0,
    0,0,0,0xFD20,0xFD20,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFD20,0xFD20,0,0,0,0,
    0,0,0,0xFD20,0xFD20,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFD20,0xFD20,0,0,0,0,
    0,0,0,0xFD20,0xFD20,0xFD20,0xFFE0,0xFFE0,0xFFE0,0xFD20,0xFD20,0xFD20,0,0,0,0,
    0,0,0,0,0xFD20,0xFD20,0xFD20,0xFFE0,0xFD20,0xFD20,0xFD20,0xFD20,0,0,0,0,
    0,0,0,0,0xFD20,0xFD20,0xFD20,0xFD20,0xFD20,0xFD20,0xFD20,0,0,0,0,0,
    0,0,0,0,0,0xFD20,0xFD20,0xFD20,0xFD20,0xFD20,0,0,0,0,0,0,
    0,0,0,0,0,0,0xFD20,0xFD20,0xFD20,0,0,0,0,0,0,0,
};

#endif // USE_OPENMOJI_DATA

